use scheduleV2;

CREATE TABLE users(
  userId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '유저 식별자',
  userName VARCHAR(20) NOT NULL COMMENT '유저 이름',
  email VARCHAR(250) NOT NULL COMMENT '이메일',
  password VARCHAR(25) NOT NULL COMMENT '비밀번호',
  createDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
  updateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '수정 시간'
);

CREATE TABLE schedules(
  scheduleId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '일정 식별자',
  title VARCHAR(250) COMMENT '일정 제목',
  schedule VARCHAR(5000) COMMENT '일정 내용',
  createDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
  updateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '수정 시간'
);