use scheduleV2;

CREATE TABLE users(
  user_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '유저 식별자',
  user_name VARCHAR(20) NOT NULL COMMENT '유저 이름',
  email VARCHAR(250) NOT NULL UNIQUE COMMENT '이메일',
  password VARCHAR(25) NOT NULL COMMENT '비밀번호',
  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
  update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '수정 시간'
);

CREATE TABLE schedules(
  schedule_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '일정 식별자',
  title VARCHAR(250) COMMENT '일정 제목',
  schedule VARCHAR(5000) COMMENT '일정 내용',
  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
  update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '수정 시간',
  user_id BIGINT COMMENT '유저 식별자',
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);